---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Activate / deactivate services
#

- name: Run service_disabling_defaults.yml
  import_tasks: service_disabling_defaults.yml

- name: Run service_sshd.yml
  import_tasks: service_sshd.yml

- name: Run service_runbg.yml
  import_tasks: service_runbg.yml
