---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025-2026: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Activate / deactivate services
#

- name: Check if openrc was used during boot-up
  import_tasks: ../tasks/was_openrc_used_to_boot_system.yml

- name: Run service_disabling_defaults.yml
  import_tasks: service_disabling_defaults.yml

- name: " Create symbolic link for /etc/init.d/rc"
  file:
    src: "{{ d_init_ift }}/rc"
    dest: "{{ d_init_d }}/rc"
    state: link
  when: ansible_facts.os_family == 'Debian'

- name: Run service_sshd.yml
  import_tasks: service_sshd.yml

- name: Run service_runbg.yml
  import_tasks: service_runbg.yml
