---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025-2026: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Install crucial apps on non Alpine distros
#

- name: "(Non Alpine) Package upgrade"
  package:
    update_cache: true
    upgrade: true

- name: "(Non Alpine) List what will be installed"
  debug:
    msg: "{{ crucial_apps | sort }}"
  run_once: true

- name: "(Non Alpine) Install crucial apps needed for deploy"
  package:
    state: present
    name: "{{ crucial_apps }}"
